# hello-chtc.sub
# My very first HTCondor submit file
s1=1344 
# start scan at this SNP index value
nsnp=41 
# length of scan in number of SNPs
index=1364
# index is location of pleiotropy peak
nboot_per_job=10
#
# Specify the HTCondor Universe (vanilla is the default and is used
#  for almost all jobs), the desired name of the HTCondor log file,
#  and the desired name of the standard error file.  
#  Wherever you see $(Cluster), HTCondor will insert the queue number
#  assigned to this set of jobs at the time of submission.
universe = vanilla
log = boot-$(Process)-$(myprocess)-run7.log
error = boot-$(Process)-$(myprocess)-run7.err
#
# Specify your executable (single binary or a script that runs several
#  commands), arguments, and a files for HTCondor to store standard
#  output (or "screen output").
#  $(Process) will be a integer number for each job, starting with "0"
#  and increasing for the relevant number of jobs.
executable = ../shell_scripts/2017-12-11_boot400-run7.sh
arguments = $(myprocess) $(nsnp) $(s1) $(index) $(nboot_per_job)
output = boot-$(Process)-$(myprocess)-run7.out
#
# Specify that HTCondor should transfer files to and from the
#  computer where each job runs. The last of these lines *would* be
#  used if there were any other files needed for the executable to run.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ../sim_data/2017-12-07_run7-400sims,../data,../Rscript,../shell_scripts,http://proxy.chtc.wisc.edu/SQUID/fjboehm/R.tar.gz,http://proxy.chtc.wisc.edu/SQUID/fjboehm/probs_17.RData,http://proxy.chtc.wisc.edu/SQUID/SLIBS.tar.gz
#
# Tell HTCondor what amount of compute resources
#  each job will need on the computer where it runs.
request_cpus = 1
request_memory = 1350MB
request_disk = 760MB
#
# extra stuff for 'materialize'
max_materialize = 5000
requirements = (OpSysMajorVer == 6) || (OpSysMajorVer == 7)

# which computer grids to use:
+WantFlocking = true
+WantGlideIn = false

# Tell HTCondor to run instances of our job:
queue myprocess from 2017-12-17_run7-boot400-badjobs2.txt

